apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    kubernetes.io/ingress.class: alb
    kubernetes.io/cluster: teraki-eks-cluster
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.name }}
              servicePort: {{ .Values.ports.port }}