apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.nodeport }}
  selector:
    name: {{ .Values.name }}